## 4-е домашнее задание - Библиотека numpy

Подпишите этот блокнот: укажите ФИО и номер группы. Выполненное задание загрузите в свой репозиторий «<b>Spring2023Python</b>» в github в папку "<b>homework04</b>".  

Перед выполнением этого домашнего задания полезно прочитать про возможности и основные методы библиотеки numpy:  
http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy  


1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [1]:
import numpy as np

In [11]:
np.linspace(-1.3, 2.5, 65)  # 65 точек - 64 отрезка.

array([-1.3     , -1.240625, -1.18125 , -1.121875, -1.0625  , -1.003125,
       -0.94375 , -0.884375, -0.825   , -0.765625, -0.70625 , -0.646875,
       -0.5875  , -0.528125, -0.46875 , -0.409375, -0.35    , -0.290625,
       -0.23125 , -0.171875, -0.1125  , -0.053125,  0.00625 ,  0.065625,
        0.125   ,  0.184375,  0.24375 ,  0.303125,  0.3625  ,  0.421875,
        0.48125 ,  0.540625,  0.6     ,  0.659375,  0.71875 ,  0.778125,
        0.8375  ,  0.896875,  0.95625 ,  1.015625,  1.075   ,  1.134375,
        1.19375 ,  1.253125,  1.3125  ,  1.371875,  1.43125 ,  1.490625,
        1.55    ,  1.609375,  1.66875 ,  1.728125,  1.7875  ,  1.846875,
        1.90625 ,  1.965625,  2.025   ,  2.084375,  2.14375 ,  2.203125,
        2.2625  ,  2.321875,  2.38125 ,  2.440625,  2.5     ])

2.	Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [12]:
import numpy as np
n = int(input())
cycle = np.array([(i % 3 + 1) for i in range(3 * n)])
print(cycle)

5
[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]


3.	Создайте массив первых 10 нечетных целых чисел.

In [7]:
import numpy as np
odd = np.array([i for i in range(20) if i % 2 == 1])
print(odd)

[ 1  3  5  7  9 11 13 15 17 19]


4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [3]:
a = np.ones((10, 10))
a[1:-1, 1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [6]:
chess = np.ones((8, 8), dtype=int)
chess[1::2, ::2] = 0
chess[::2, 1::2] = 0
print(chess)

# 1 - белая клетка
# 0 - чёрная клетка

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [7]:
n = int(input())
m = np.arange(n ** 2)
print((m // n + m % n).reshape(n, n))

# Как в математике

5
[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [9]:
matrix = np.arange(1, 10).reshape(3, 3)
matrix_reloaded = np.arange(11, 20).reshape(3, 3)
vector_1 = np.array([1, 2, 3])
vector_2 = np.array([-1, 0, 1])

print(np.dot(vector_1, vector_2))
print(np.dot(matrix, vector))
print(np.dot(matrix, matrix_reloaded))

2
[14 32 50]
[[ 90  96 102]
 [216 231 246]
 [342 366 390]]


8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [27]:
x = np.arange(0, 1.05, 0.05)
cos = np.cos(x)
sin = np.sin(x)

print(np.vstack((cos, sin)))

[[1.         0.99875026 0.99500417 0.98877108 0.98006658 0.96891242
  0.95533649 0.93937271 0.92106099 0.9004471  0.87758256 0.85252452
  0.82533561 0.7960838  0.76484219 0.73168887 0.69670671 0.65998315
  0.62160997 0.58168309 0.54030231]
 [0.         0.04997917 0.09983342 0.14943813 0.19866933 0.24740396
  0.29552021 0.34289781 0.38941834 0.43496553 0.47942554 0.52268723
  0.56464247 0.60518641 0.64421769 0.68163876 0.71735609 0.75128041
  0.78332691 0.8134155  0.84147098]]


9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [10]:
np.random.rand(3, 5) * 4 - 1
# EZ

array([[ 2.11741373,  2.98382182, -0.08017527,  0.53762474,  1.58569118],
       [-0.35738302,  2.18390944,  1.02698938, -0.32013668,  0.84642228],
       [ 2.57085885, -0.07038243,  2.1893022 ,  1.59759088,  2.1257642 ]])

10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [10]:
A = np.array([[ 2.11741373,  2.98382182, -0.08017527,  0.53762474,  1.58569118],
       [-0.35738302,  2.18390944,  1.02698938, -0.32013668,  0.84642228],
       [ 2.57085885, -0.07038243,  2.1893022 ,  1.59759088,  2.1257642 ]])

print(A.sum())
print(A.sum(axis=1))  # По строкам
print(A.sum(axis=0))  # По столбцам
print(A.mean(axis=1))  # Срзнач
print(A.var(axis=1))  # У меня дисперсия
print(A.std(axis=1))  # Стандарт дивиейшн

18.9373113
[7.1443762 3.3798014 8.4131337]
[4.33088956 5.09734883 3.13611631 1.81507894 4.55787766]
[1.42887524 0.67596028 1.68262674]
[1.19761925 0.89723938 0.86446387]
[1.09435792 0.94722721 0.92976549]


11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [14]:
A = np.random.uniform(-1,3,15).reshape(3,5)
x = np.average(A, axis=-1)
y = np.sqrt(np.var(A, axis=-1, dtype=float))
print((A - x.reshape(len(x), 1)) / y.reshape(len(y), 1))

[[-1.27845498 -0.85369275 -0.13388783  0.97274137  1.29329418]
 [-1.32165409 -0.76428798 -0.08629474  0.69731176  1.47492505]
 [-0.07764217  1.32090472  0.90993993 -1.30359382 -0.84960866]]


12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [15]:
A = np.random.uniform(-1, 3, 15).reshape(3, 5).transpose()
A[A[:, 2].argsort()]

array([[-0.54297045,  0.88557694, -0.53164162],
       [-0.34164345,  0.58700238,  0.79010949],
       [-0.29652659,  0.25402533,  1.36629019],
       [-0.33190629, -0.81760474,  1.39376729],
       [ 0.06039182,  0.01700007,  1.9890234 ]])

13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [16]:
A = np.random.uniform(-1, 3, 15).reshape(3, 5)
B = A.dot(A.T)
C = A.T.dot(A)
print('В =', B)
print('C =', C)

# Матрица В имеет размеры 3х3, матрица С - 5х5.

В = [[10.79279427  5.63400518 -0.69903177]
 [ 5.63400518  8.16570934  1.04800334]
 [-0.69903177  1.04800334  9.0193649 ]]
C = [[ 8.50600148  3.99163323  0.0666537   5.17229153  1.68234811]
 [ 3.99163323  3.93131659  3.55883714  1.34122112  0.43211941]
 [ 0.0666537   3.55883714  6.04705361 -1.87113097 -0.58824508]
 [ 5.17229153  1.34122112 -1.87113097  8.85051607  0.08293016]
 [ 1.68234811  0.43211941 -0.58824508  0.08293016  0.64298077]]


14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [18]:
print(np.trace(B))
print(np.trace(C))

27.977868514291252
27.977868514291252


15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


In [27]:
print('Ранг матрицы A =', np.linalg.matrix_rank(A),'\nМатрица не является квадратной! Определитель и спектр матрицы A посчитать нельзя!')
print()

print('Ранг матрицы В =', np.linalg.matrix_rank(B), '\nОпределитель матрицы В =', np.linalg.det(B))
w, v = np.linalg.eig(B)
print("Собственные значения матрицы В:\n", w)
print()

print('Ранг матрицы C =', np.linalg.matrix_rank(C), '\nДетерминант матрицы C = ', np.linalg.det(C))
w, v = np.linalg.eig(C)
print("Собственные значения матрицы C:\n", w)

# Ранги равны. Длины спектров равны размерностям матриц В и С.

Ранг матрицы A = 3 
Матрица не является квадратной! Определитель и спектр матрицы A посчитать нельзя!

Ранг матрицы В = 3 
Определитель матрицы В = 484.4924372879269
Собственные значения матрицы В:
 [15.2661232   3.41297018  9.29877513]

Ранг матрицы C = 3 
Детерминант матрицы C =  -2.1452935036629124e-29
Собственные значения матрицы C:
 [ 1.52661232e+01 -1.02175213e-15  3.41297018e+00  9.29877513e+00
 -6.91531254e-16]


16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять два из следующих примеров:  
- один с номером, сгенерированным случайным образом с помощью функции np.random.randint(9), в качестве seed для генератора случайных чисел взять номер своего студенческого билета. 
- второй номер - под номером 9, несобственный интерграл. Подумайте, как сделать подбор шага интегрирования адаптивным.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        <td> 9) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        </tr>
</table>